export const productData = [
  "https://images.pexels.com/photos/1656663/pexels-photo-1656663.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/219794/pexels-photo-219794.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/928251/pexels-photo-928251.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/89267/pexels-photo-89267.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/1400171/pexels-photo-1400171.jpeg?auto=compress&cs=tinysrgb&w=600",
  "https://images.pexels.com/photos/1367243/pexels-photo-1367243.jpeg?auto=compress&cs=tinysrgb&w=600",
];

export let data = [
  {
    sno: 1,
    Varitey: "Onion",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
    Description:
      "onion also known as the bulb onion or common onion, is a vegetable that is the most widely cultivated species of the genus Allium.",
  },
  {
    sno: 2,
    Varitey: "Tomato",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
    Description:
      "tomatoes&nbsp;are small,&nbsp;soft, red fruit that you can eat&nbsp;raw&nbsp;in salads or&nbsp;cooked&nbsp;as a vegetable",
  },
  {
    sno: 3,
    Varitey: "Potato",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
    Description:
      "Potatoes&nbsp;are edible tubers, available worldwide and all year long. They are relatively cheap to grow, rich in nutrients, and they can make a delicious treat",
  },
  {
    sno: 4,
    Varitey: "sweet potato",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
    Description:
      "Sweet potatoes&nbsp;are a staple food in many parts of the world. They are a good source of fiber, potassium, vitamins, and other essential nutrients",
  },
  {
    sno: 5,
    Varitey: "carrot",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
    Description:
      "The&nbsp;carrot&nbsp; is a root vegetable often claimed to be the perfect health food. It is crunchy, tasty, and highly nutritious.",
  },
  {
    sno: 6,
    Varitey: "beetroot",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
    Description:
      "Beetroot&nbsp; is a root vegetable also known as red beet, table beet, garden beet, or just beet. Packed with essential nutrients",
  },
  {
    sno: 7,
    Varitey: "Cucumber",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
    Description:
      "Cucumbers have a mild, refreshing taste and a high water content. They can help relieve dehydration and are pleasant to eat in hot weather.\n",
  },
  {
    sno: 8,
    Varitey: "lemon Cucumber",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
    Description:
      "Lemon cucumbers&nbsp;have no lemon flavor and their skin is slightly thicker and the center is more seedy as the fruit stays on the vine longer",
  },
  {
    sno: 9,
    Varitey: "ridge guard",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
    Description:
      "Ridge gourd is a water vegetable housing ample amounts of liquid content, which confer remarkable cooling effects and reduce excessive body heat",
  },
  {
    sno: 10,
    Varitey: "bitter guard",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
    Description:
      "Bitter gourd&nbsp;is a rich source of vitamin C, which helps fight many diseases, and wound healing and is crucial for development and growth",
  },
  {
    sno: 11,
    Varitey: "Snake guard",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 12,
    Varitey: "Little guard",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 13,
    Varitey: "ladies finger",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 14,
    Varitey: "Capsicum",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 15,
    Varitey: "French beans",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 16,
    Varitey: "broad beans",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 17,
    Varitey: "clustter bean",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 18,
    Varitey: "brinjal purple long",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 19,
    Varitey: "brinjal green round",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 20,
    Varitey: "Brinjal purple round",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 21,
    Varitey: "Colocasia(chama gadda)",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 22,
    Varitey: "Green chilli",
    Catogery: "veggies",
    sku: 0.25,
    Units: "kg",
  },
  {
    sno: 23,
    Varitey: "Ginger",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 24,
    Varitey: "Garlic",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 25,
    Varitey: "amla",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 26,
    Varitey: "Chow chow",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 27,
    Varitey: "Knol knol",
    Catogery: "veggies",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 28,
    Varitey: "Cauliflower",
    Catogery: "veggies",
    sku: 1,
    Units: "pc",
  },
  {
    sno: 29,
    Varitey: "Cabbage",
    Catogery: "veggies",
    sku: 1,
    Units: "pc",
  },
  {
    sno: 30,
    Varitey: "Bottle guard",
    Catogery: "veggies",
    sku: 1,
    Units: "pc",
  },
  {
    sno: 31,
    Varitey: "Raw banana",
    Catogery: "veggies",
    sku: 1,
    Units: "pc",
  },
  {
    sno: 32,
    Varitey: "Radish",
    Catogery: "veggies",
    sku: 1,
    Units: "pc",
  },
  {
    sno: 33,
    Varitey: "Sweet pumpkin",
    Catogery: "veggies",
    sku: 1,
    Units: "kg",
  },
  {
    sno: 34,
    Varitey: "white Pumpkin",
    Catogery: "veggies",
    sku: 1,
    Units: "kg",
  },
  {
    sno: 35,
    Varitey: "banana Flower",
    Catogery: "veggies",
    sku: 1,
    Units: "pc",
  },
  {
    sno: 36,
    Varitey: "Sweet corn",
    Catogery: "veggies",
    sku: 1,
    Units: "pc",
  },
  {
    sno: 37,
    Varitey: "lemon ",
    Catogery: "veggies",
    sku: 1,
    Units: "pc",
  },
  {
    sno: 38,
    Varitey: "Coconut",
    Catogery: "veggies",
    sku: 1,
    Units: "pc",
  },
  {
    sno: 39,
    Varitey: "Banana stem",
    Catogery: "veggies",
    sku: 1,
    Units: "pc",
  },
  {
    sno: 40,
    Varitey: "Drumstick",
    Catogery: "veggies",
    sku: 1,
    Units: "pc",
  },
  {
    sno: 41,
    Varitey: "Mushroom",
    Catogery: "veggies",
    sku: 1,
    Units: "Case",
  },
  {
    sno: 42,
    Varitey: "Baby corn",
    Catogery: "veggies",
    sku: 1,
    Units: "Case",
  },
  {
    sno: 43,
    Varitey: "Spring onion",
    Catogery: "veggies",
    sku: 0.2,
    Units: "kg",
  },
  {
    sno: 44,
    Varitey: "Spinach",
    Catogery: "veggies",
    sku: 0.2,
    Units: "kg",
  },
  {
    sno: 45,
    Varitey: "amaranthus",
    Catogery: "veggies",
    sku: 0.2,
    Units: "kg",
  },
  {
    sno: 46,
    Varitey: "Rossel leaves",
    Catogery: "veggies",
    sku: 0.2,
    Units: "kg",
  },
  {
    sno: 47,
    Varitey: "fenugreek",
    Catogery: "veggies",
    sku: 0.2,
    Units: "kg",
  },
  {
    sno: 48,
    Varitey: "cylon spinach",
    Catogery: "veggies",
    sku: 0.2,
    Units: "kg",
  },
  {
    sno: 49,
    Varitey: "corriender",
    Catogery: "veggies",
    sku: 0.2,
    Units: "kg",
  },
  {
    sno: 50,
    Varitey: "curry leaves",
    Catogery: "veggies",
    sku: 0.05,
    Units: "kg",
  },
  {
    sno: 51,
    Varitey: "mint",
    Catogery: "veggies",
    sku: 0.1,
    Units: "kg",
  },
  {
    sno: 52,
    Varitey: "Banana G-9",
    Catogery: "Fruits",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 53,
    Varitey: "Guva White",
    Catogery: "Fruits",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 54,
    Varitey: "Sapota",
    Catogery: "Fruits",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 55,
    Varitey: "Banana yellanki",
    Catogery: "Fruits",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 56,
    Varitey: "Pomogranate",
    Catogery: "Fruits",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 57,
    Varitey: "Apple",
    Catogery: "Fruits",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 58,
    Varitey: "Mosambi",
    Catogery: "Fruits",
    sku: 0.5,
    Units: "kg",
  },
  {
    sno: 59,
    Varitey: "Pappaya",
    Catogery: "Fruits",
    sku: 1,
    Units: "pc",
  },
  {
    sno: 60,
    Varitey: "Pineapple",
    Catogery: "Fruits",
    sku: 1,
    Units: "pc",
  },
];
